### ISSUE TITLE
management

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/kastenwesen#14]
- [x] `kastenwesen restart` on boot
- [x] status page
- [x] watchdog mail
- [x] security update mail

**Comment by sedrubal** [comment]
Is it possible to make the cronjob more "pythonic" and move it in kastenwesen (e.g. `kastenwesen cron`)? Or we should at least use [`ansi2html`](https://pypi.python.org/pypi/ansi2html/1.1.0), because `aha` is not available on all distros...

**Comment by mgmax** [comment]
Feel free to do so ;-)
