### ISSUE TITLE
Travis Build unzuverlässig

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/kastenwesen#26]
manchmal schlagen die Builds fehl, weil der Netzwerktest für test2 fehlschlägt. Neustart des Builds löst das Problem. Keine Ahnung wieso, Timing??

**Comment by patkan** [comment]
Das ist mir auch schon aufgefallen. Ich hatte den Eindruck, dass das vor allem passiert, wenn die travis-Maschinen mal wieder besonders langsam sind. Das ist aber rein subjektiv, könnte zumindest für timing-Geschichten sprechen.

**Comment by patkan** [comment]
Heute wieder: beim dritten neu bauen ist es dann durchgelaufen.

**Comment by mgmax** [comment]
Einfach mehr sleep, wenn travis erkannt wird?

**Comment by patkan** [comment]
Hört sich sinnvoll an. Zumindest fällt mir nichts anderes ein.

**Comment by patkan** [comment]
Siehe #29 
Ich bin etwas ratlos. Scheinbar ist es keine Timing-Geschichte. Oder übersehe ich da was?

**Comment by mgmax** [comment]
sleep_before_test wirkt nur bei Aktionen wir start/stop. Der Fehler tritt hier bei `status` auf, evtl weil `socat` im test2 Container nach einer Verbindung nicht schnell genug wieder auf neue Verbindungen reagiert. Wenn schon, dann müsste man eine Wartezeit vor `status` im Test-Ablauf ergänzen.

**Comment by patkan** [comment]
Jetzt müsste es passen, tut es aber nicht. Oder fehlt noch etwas?
