### ISSUE TITLE
Remove old containers and images

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/kastenwesen#43]
Kastenwesen should remove exited containers and unlabelled images. Currently our docker partition is full and the containers are failing because there is `no space left on device`. This is a quick and dirty fix:

```sh
docker ps -a | grep 'Exited' | awk '{print $1}' | xargs --no-run-if-empty sudo docker rm
docker images | grep '<none>' | awk '{print $3}'  | xargs --no-run-if-empty sudo docker rmi
```

**Comment by mgmax** [comment]
there is "kastenwesen clean" exactly for this
