### ISSUE TITLE
Don't lock for `shell`

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/kastenwesen#48]
I think there is no reason to block other instances of kastenwesen, when running `kastenwesen shell`.
Is there a reason to lock at all? I think docker knows what it is doing...

**Comment by mgmax** [comment]
Restarting or rebuilding the container is problematic while a shell session is open, especially in the same instance.

**Comment by sedrubal** [comment]
But now it is not possible to run more than one shell command at once. This is more bad than a crashing shell caused by a rebuild.
