### ISSUE TITLE
Kastenwesen status emails should not be send twice

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/kastenwesen#55]
Currently admins get spammed by `kastenwesen status` mails if there is an error. We should send only one email and if there is no change, we shouldn't send the same email again.

**Comment by mgmax** [comment]
Yes, there should be fewer emails.
When fixing this we have to make sure that the following events are still clear from looking at the emails:
- error has gone, i.e. the previous alarm can be ignored
- error has become significantly worse (e.g. while one unimportant container is broken, others start failing as well)
